# Generated by Django 4.0.4 on 2022-05-05 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iap_cash', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('renown', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('plots', models.JSONField(null=True)),
                ('barracks', models.JSONField(null=True)),
                ('current_hero', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('area_unlock', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
